global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    instance: '18.217.148.69'

rule_files:
  - "blackbox-rules-ec2-prod.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Service Registry (Eureka)
  - job_name: 'service-registry'
    static_configs:
      - targets: ['service-registry:8761']
    metrics_path: /actuator/prometheus
    scrape_interval: 30s
    scrape_timeout: 10s

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8081']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    scrape_timeout: 10s

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    scrape_timeout: 10s

  # Category Service
  - job_name: 'category-service'
    static_configs:
      - targets: ['category-service:8082']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    scrape_timeout: 10s

  # Product Service
  - job_name: 'product-service'
    static_configs:
      - targets: ['product-service:8083']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    scrape_timeout: 10s

  # Cart Service
  - job_name: 'cart-service'
    static_configs:
      - targets: ['cart-service:8084']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    scrape_timeout: 10s

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:8085']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    scrape_timeout: 10s

  # Order Service
  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8086']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    scrape_timeout: 10s

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8087']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    scrape_timeout: 10s

  # Node Exporter (Host metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Blackbox Exporter (HTTP monitoring)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://18.217.148.69/health
        - http://18.217.148.69:8081/actuator/health
        - http://18.217.148.69:8761/actuator/health
        - https://18.217.148.69/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Nginx monitoring (if nginx-exporter is enabled)
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # MongoDB monitoring
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongodb:27017']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Grafana monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Promtail (Log aggregation)
  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Application specific endpoints
  - job_name: 'application-endpoints'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://18.217.148.69/api/product-service/products
        - http://18.217.148.69/api/category-service/categories
        - http://18.217.148.69/api/auth-service/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # SSL certificate monitoring
  - job_name: 'ssl-certificates'
    metrics_path: /probe
    params:
      module: [ssl_connect]
    static_configs:
      - targets:
        - 18.217.148.69:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115 