spring:
    application:
        name: user-service

    data:
        mongodb:
            uri: mongodb://admin:password@mongodb:27017/purely_user_service?authSource=admin
            #authentication-database: admin
            #username: rootuser
            #password: rootpass        
            #auto-index-creation: true             
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 8086

eureka:
    client:
        serviceUrl:
            defaultZone: http://service-registry:8761/eureka/
    instance:
        prefer-ip-address: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        prometheus:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true

queueit:
  customer-id: "futuraforge"
  secret-key: "62cc5b6d-cad7-44c5-88a2-34fa78f73b767c7dcee7-5e81-44c4-93ea-0990c14f3176"
  api-key: "4607e3f0-dcb2-4714-9570-45d7e662c45f"
  queue-domain: your-actual-queue-domain.queue-it.net
  enabled: true
  debug: false